rails/config/routes.rb
LearningStyleManager::Application.routes.draw do
  resources(:students, only: [:show]) do
    resources :star, only: [:new, :create, :show], controller: 'star_test'
    resources :dol5, only: [:new, :create, :show], controller: 'dol5_test'
    resources :gmit, only: [:new, :create, :show], controller: 'gmit_test'
    resources :ausidentities, only: [:new, :create, :show], controller: 'ausidentities_test'
    member do
      get 'dashboard', to: 'students#dashboard'
    end
  end
  
  get "teachers/dashboard", to: "teacher#dashboard"
  get "teachers/school-results", to: "teacher#school_results"
  
  root "home#index"
  post "login", to: "home#login"
  get  "logout", to: "home#logout"
end

rails/app/views/shared/_menu.html.erb
<% if is_student %>
<nav class="navbar navbar-static-top" role="navigation">
	<a class="navbar-brand">Learning Style Manager</a>
	<ul class="nav navbar-nav">
		<li class="<%= "active" if current_page?(dashboard_student_path(current_student)) %>"><a href="<%= dashboard_student_path(current_student) %>">Dashboard</a></li>
		<li class="dropdown <%= "active" if (controller_name == "ausidentities_test") or (controller_name == "dol5_test") or
      (controller_name == "gmit_test") or
      (controller_name == "star_test") %>">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Test <b class="caret"></b></a>
		<ul class="dropdown-menu">
			<li><a href="<%= new_student_star_path(current_student) %>">STAR (Spatial Tactile Auditory Reading)</a></li>
			<li><%= link_to "DOL5 (Dimensions of Learning)", new_student_dol5_path(current_student) %>
			<li><a href="<%= new_student_gmit_path(current_student) %>">GMIT (Gardner's Multiple Intelligences)</a></li>
			<li><a href="<%= new_student_ausidentity_path(current_student) %>">AusIdentities</a></li>
		</ul>
		</li>
		<li class="<%= "active" if current_page?(student_path(current_student)) %>"><a href="<%= student_path(current_student) %>">Results</a></li>
	</ul>
	<form class="navbar-form navbar-right"><a href="/logout" class="btn btn-default" role="button">Logout</a></form>
</nav>

<% elsif is_teacher %>
<nav class="navbar navbar-static-top" role="navigation">
	<a class="navbar-brand">Learning Style Manager</a>
	<ul class="nav navbar-nav">
		<li class="active"><a href="/teachers/dashboard">Dashboard</a></li>
		<li><a href="/teachers/school-results">School results</a></li>
	</ul>
	
	<form class="navbar-form navbar-left" role="search">
		<div class="form-group">
			<input type="text" class="form-control" placeholder="Search students">
		</div>
	</form>
	
	<form class="navbar-form navbar-right"><a href="/logout" class="btn btn-default" role="button">Logout</a></form>
</nav>
<% end %>